### ISSUE TITLE
dangerous behavior when acquisition_cell fails

### ISSUE THREAD

**Issue by SamuelDeleglise** [kyrylo-gr/labmate#25]
I quite often encounter an annoying scenario:
  1. You modify the configuration.py
  2. you re-run the same acquisition_cell... 
  3. There's an autoreload problem, or the sequence won't compile or anything that prevents the new acquisition from being launched...
  4. Unfortunately, you don't notice this because you don't look at the exception traceback, or because you don't notice the print of the failed autoreload
  5. You run the analysis cell and end-up re-analyzing the old data, unfortunately, in the mean-time the metadata corresponding to your new configuration have been saved in the temp file
  6. You scratch your head wondering why the curves didn't change the way you were expecting (why they didn't  change at all actually).
  7. Eventually, you scroll up and notice that in fact you are still analyzing a run that was launched with the old parameters... 
--->Unfortunately, the saved data and figures don't have the right metadata, which is very annoying.

I guess the solution to this problem is not unique: 
 a. updating temp only once the acquisition_cell execution is over (and no exception occured) would at least prevent the wrong metadata from being saved with the new data, but anyways, it is not great because some parameters might have changed (like the yoko voltage for instance) while others would not (like the if_frequencies for instance) ---> This is not ideal.
 b. In fact we should maybe go further and really prevent from analyzing anything when the acquisition_cell didn't go to the last statement '''job = execute(program)''', this could be done very simply by setting '''job = None''' in the init_acquisition_cell.py. As I understood, anyways, you are working at pickling the job, so we should probably think of a solution where the pickle is set to None at the beginning of acquisition_cells ?
 c. Even all this is not ideal in the case where autoreload has silently failed (for instance, imagine a syntax error in configuration.py), then you would create a job with the wrong parameter and analyze it... For this, I am not sure how to do... Maybe there's a way to force an exception when autoreload fails...

**Comment by kyrylo-gr** [comment]
Should be fixed with new push
