### ISSUE TITLE
parse_config doesn't convert to float when negative sign is present

### ISSUE THREAD

**Issue by SamuelDeleglise** [kyrylo-gr/labmate#34]

**Comment by SamuelDeleglise** [comment]
Is this one solved already ? It is extremely painful...

Also, once you have solved a bug, what should  I do now that we are on Pypy: pip install --update labmate ?

**Comment by SamuelDeleglise** [comment]
OK, I installed in develop mode on the experiment control computer... I saw it's already fixed since 2 days on git...

**Comment by kyrylo-gr** [comment]
Yes, now it's fixed on the git and will be fixed on the pypi with the new release
