### ISSUE TITLE
Rational for init_acquisition_cell.py

### ISSUE THREAD

**Issue by SamuelDeleglise** [kyrylo-gr/labmate#39]
we need to switch from the current system where the parameters such as yoko voltage, anapico frequencies and powers are totally undefined to a system where at the beginning of each acquisition, the parameters are set according to variables in the config file.

It seems to me like the cleanest way to do that would be to implement the init_acquisition_cell.py call in labmate.

**Comment by kyrylo-gr** [comment]
solved in new v0.4.0
