### ISSUE TITLE
Make sure right variable are saved in save_acquisition

### ISSUE THREAD

**Issue by lkb-omq** [kyrylo-gr/labmate#82]
# Do not allow to use variable in analysis with the same name that were saved with save_acquisition
```
aqm.save_acquisition(
        **res,
        element=element,
        )
```
This do not raise a warning `element = aqm.d.element`. However it changes the variable that will be saved later.
This means that if one runs:
- current analysis
- old analysis
- current analysis

Problem: It will save the variable from old analysis into current one.

# Make possibility to save variable ones

Something like
```
aqm.save_initial_acquisition( # runs only ones if variables are not saved before
        element=element,
        )
aqm.up_acquisition( # runs every time
        **res,
        )
```
This would solved the previous problem

**Comment by kyrylo-gr** [comment]
Solved in dbfb438 by adding `update` argument

```
aqm.save_acquisition(  # Save params when they don't yet exist
    True,
    param1=1
)
aqm.save_acquisition(  # Runs every time
        **res,
        )
```
